server:
  port: 8081

spring:
  kafka:
    consumer:
      bootstrap-servers: localhost:9095, localhost:9096, localhost:9097
      ssl:
        trust-store-location: file:/Users/dmcheremisin/Workspace/ssl/client.truststore.jks
        trust-store-password: 123456
        key-store-location: file:/Users/dmcheremisin/Workspace/ssl/client.keystore.jks
        key-store-password: 123456
      properties:
        security:
          protocol: SSL
    producer:
      bootstrap-servers: localhost:9095, localhost:9096, localhost:9097
      properties:
        security:
          protocol: SSL
        ssl.endpoint.identification.algorithm:
